title = "Rahemos"
baseURL = "https://rahemos.com"
languageCode = "en-us"
theme = 'ananke'

SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
omit_header_text = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Emaleth"
  favicon = ""
  site_logo = ""
  description = "Rahemos game website"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  show_reading_time = true
  

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rahemos_game"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/Emaleth"